### ISSUE TITLE
#1 Team Members Missing.

### ISSUE THREAD

**Issue by dbc2201** [Surbhi1104/Personal-Doc#1]
Please add other team members in the repository as well.

**Comment by Surbhi1104** [comment]
**issue resolved**

**Comment by dbc2201** [comment]
Still no contributors 
![screenshot from 2019-02-17 19-22-32](https://user-images.githubusercontent.com/22192936/52914007-7c8e9a80-32e9-11e9-8636-9810a8857f5c.png)
